FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app/src
COPY ./ .
RUN dotnet restore logger/SurronCommunication_Importer/SurronCommunication_Importer.csproj
RUN dotnet publish -c Release logger/SurronCommunication_Importer/SurronCommunication_Importer.csproj -o /app/build

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app/build/ ./
ENTRYPOINT ["dotnet", "SurronCommunication_Importer.dll"]